export const ORDERS = [
  {
    id: "#CM9801",
    user: "Natali Craig",
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
  },
  {
    id: "#CM9802",
    user: "Kate Morrison",
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
  },
  {
    id: "#CM9803",
    user: "Drew Cano",
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
  },
  {
    id: "#CM9804",
    user: "Orlando Diggs",
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Approved",
  },
  {
    id: "#CM9805",
    user: "Andi Lane",
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
  },
  {
    id: "#CM9806",
    user: "Rosa Lindsey",
    project: "Marketing Site",
    address: "Ocean Ave Miami",
    date: "Feb 3, 2023",
    status: "Approved",
  },
  {
    id: "#CM9807",
    user: "Peter Yang",
    project: "Billing Service",
    address: "Elm Street Austin",
    date: "Feb 4, 2023",
    status: "Pending",
  },
  {
    id: "#CM9808",
    user: "Sara Khan",
    project: "Portfolio",
    address: "Oxford Road London",
    date: "Feb 5, 2023",
    status: "Complete",
  },
  {
    id: "#CM9809",
    user: "Luis Gomez",
    project: "CRM Widgets",
    address: "Sunset Blvd LA",
    date: "Feb 6, 2023",
    status: "In Progress",
  },
  {
    id: "#CM9810",
    user: "Abby Holt",
    project: "Dashboard Revamp",
    address: "Willow Lane Denver",
    date: "Feb 7, 2023",
    status: "Rejected",
  },
  {
    id: "#CM9801",
    user: "Natali Craig",
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
  },
  {
    id: "#CM9802",
    user: "Kate Morrison",
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
  },
  {
    id: "#CM9803",
    user: "Drew Cano",
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
  },
  {
    id: "#CM9804",
    user: "Orlando Diggs",
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Approved",
  },
  {
    id: "#CM9805",
    user: "Andi Lane",
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
  },
  {
    id: "#CM9811",
    user: "Chloe Park",
    project: "Payment Gateway",
    address: "Market Street SF",
    date: "Feb 8, 2023",
    status: "Approved",
  },
  {
    id: "#CM9812",
    user: "Ivan Petrov",
    project: "ML Pipeline",
    address: "Nevsky Prospect SPB",
    date: "Feb 9, 2023",
    status: "Complete",
  },
  {
    id: "#CM9813",
    user: "Ava Patel",
    project: "iOS App",
    address: "MG Road Bangalore",
    date: "Feb 10, 2023",
    status: "Pending",
  },
  {
    id: "#CM9814",
    user: "Noah Kim",
    project: "Android App",
    address: "Gangnam Seoul",
    date: "Feb 11, 2023",
    status: "In Progress",
  },
  {
    id: "#CM9815",
    user: "Emma Wilson",
    project: "Analytics",
    address: "Queen St Toronto",
    date: "Feb 12, 2023",
    status: "Approved",
  },
  {
    id: "#CM9816",
    user: "Jack Brown",
    project: "Email Service",
    address: "King's Cross London",
    date: "Feb 13, 2023",
    status: "Rejected",
  },
  {
    id: "#CM9817",
    user: "Maya Singh",
    project: "Onboarding",
    address: "Brigade Rd Bangalore",
    date: "Feb 14, 2023",
    status: "Pending",
  },
  {
    id: "#CM9818",
    user: "Leo Martinez",
    project: "Data Warehouse",
    address: "Liberty Ave NYC",
    date: "Feb 15, 2023",
    status: "Complete",
  },
  {
    id: "#CM9819",
    user: "Olivia Chen",
    project: "SEO Audit",
    address: "Orchard Rd Singapore",
    date: "Feb 16, 2023",
    status: "Approved",
  },
  {
    id: "#CM9820",
    user: "Henry Lee",
    project: "Blog Engine",
    address: "Mission St SF",
    date: "Feb 17, 2023",
    status: "In Progress",
  },
  {
    id: "#CM9821",
    user: "Sophia Rossi",
    project: "Landing A/B Test",
    address: "Via Roma Milan",
    date: "Feb 18, 2023",
    status: "Pending",
  },
  {
    id: "#CM9822",
    user: "Ethan Clark",
    project: "Chatbot",
    address: "Bourke St Melbourne",
    date: "Feb 19, 2023",
    status: "Complete",
  },
  {
    id: "#CM9823",
    user: "Layla Ahmed",
    project: "Docs Portal",
    address: "Zamalek Cairo",
    date: "Feb 20, 2023",
    status: "Rejected",
  },
  {
    id: "#CM9824",
    user: "Lucas Silva",
    project: "Scheduler",
    address: "Paulista Ave Sao Paulo",
    date: "Feb 21, 2023",
    status: "Approved",
  },
  {
    id: "#CM9825",
    user: "Isla Thompson",
    project: "Support Desk",
    address: "George St Sydney",
    date: "Mar 1, 2023",
    status: "Complete",
  },
];

export const statusToClass = (s) =>
  ({
    "In Progress": "progress",
    Pending: "pending",
    Approved: "approved",
    Rejected: "rejected",
    Complete: "complete",
  }[s] || "pending");
